version: '3.9'
services:
  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8080"
      # ช่วยให้ไฟล์วอชบน Windows เด้งเสมอ
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on: [gateway]

  auth-service:
    build: ./Authentication-Service
    ports: ["4001:4001"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 4001
      CHOKIDAR_USEPOLLING: "true"   # เผื่อใช้ nodemon/chokidar
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./Authentication-Service:/app
      - /app/node_modules

  appointment-service:
    build: ./Appointment-service
    ports: ["4002:4002"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 4002
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./Appointment-service:/app
      - /app/node_modules

  gateway:
    image: nginx:1.27
    ports: ["8080:8080"]
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [auth-service, appointment-service]
