version: '3.9'
services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8080"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    command: npm run dev
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on: [gateway]
    networks: [appnet]

  auth-service:
    build: ./Authentication-Service
    expose:
      - "4001"
    ports:
      - "5001:4001"             
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 4001           
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./Authentication-Service:/app
      - /app/node_modules
    networks: [appnet]

  appointment-service:
    build: ./Appointment-service
    expose:
      - "4002"  
    ports:
      - "5002:4002"       
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 4002            
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./Appointment-service:/app
      - /app/node_modules
    networks: [appnet]

  gateway:
    image: nginx:1.27
    ports:
      - "8080:8080"  
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [auth-service, appointment-service]
    networks: [appnet]

networks:
  appnet:
    driver: bridge