version: '3.9'
services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    command: npm run dev
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on: [gateway]
    networks: [appnet]

  auth-service:
    build: ./Authentication-Service
    expose:
      - "4001"
    ports:
      - "5001:4001"             
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      PORT: 4001           
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./Authentication-Service:/app
      - /app/node_modules
    networks: [appnet]

  appointment-service:
    build: ./Appointment-service
    expose:
      - "4002"  
    ports:
      - "5002:4002"       
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      PORT: 4002            
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./Appointment-service:/app
      - /app/node_modules
    networks: [appnet]

  pharmacy-service:
    build: ./svc-pharmacy
    expose:
      - "4003"  
    ports:
      - "5003:4003"       
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      PORT: 4003            
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./svc-pharmacy:/app
      - /app/node_modules
    networks: [appnet]

  payment-service:
    build: ./Payment-Service
    expose:
      - "4004"  
    ports:
      - "5004:4004"       
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      PORT: 4004            
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./Payment-Service:/app
      - /app/node_modules
    networks: [appnet]

  profile-service:
    build: ./svc-doctor-profile
    expose:
      - "4005"  
    ports:
      - "5005:4005"       
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      PORT: 4005            
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./svc-doctor-profile:/app
      - /app/node_modules
    networks: [appnet]

  gateway:
    image: nginx:1.27
    ports:
      - "9000:8080"  
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [auth-service, appointment-service, pharmacy-service, payment-service]
    networks: [appnet]

networks:
  appnet:
    driver: bridge